requirements.txt

Mainly, this fixes the `JWT_ALGORITHMS` bug in previous versions, which
DGPF fixed manually in auth.py.

chore: Bump major social auth version in requirements to 5

---

globus_portal_framework/gclients.py

The new lazy imports remove references which would otherwise exist, which
DGPF relies on for supporting older versions of the Globus SDK.

fix: New lazy-imports feature in globus-sdk 3.9 causing error on startup

---

globus_portal_framework/__init__.py

No longer required in Django 3+

chore: Remove default app config

---

globus_portal_framework/views/generic.py

Facet modifiers were not properly loaded for a given search index if the view was constructed using generics.

fix: facet modifiers for generic views

---

.github/workflows/publish.yml
MANIFEST.in
setup.py

Build and publish packages using github actions. Minor fixes added for setuptools. Tests are now pruned from releases.

Add PyPi Publish Workflow on Github Actions

---

globus_portal_framework/views/generic.py

DEFAULT_RESULT_FORMAT_VERSION was not used for setting the default search setting, causing a problem now that the version has been changed.

fix: Generic views not inline with the default portal search settings

---

globus_portal_framework/auth.py
globus_portal_framework/checks.py
globus_portal_framework/gclients.py
globus_portal_framework/views/base.py
tests/conftest.py
tests/test_auth.py
tests/test_gclients.py
tests/test_views.py

A handful of code, mainly around groups, was not yet implemented in the Globus SDK and had to be implemented here manually. That has now been removed, simplifying calls into the Globus API.

refactor: Remove old globus-sdk v2 era code

---

README.rst

Now that all issues are tracked in Shortcut instead of on Github here, let the user know that opening issues here are still acceptable and encouraged.

docs: Add "Issues" section to README

---

docs/source/reference/settings_example.py

It wasn't there before, showing only basic config items. But SEARCH_INDEXES is used for the most widespread portal type so we should add it there

docs: Add SEARCH_INDEXES to example conf file

---

requirements.txt

Add support for the Django 5 Release https://docs.djangoproject.com/en/5.0/releases/5.0/
No action needs to be taken here for DGPF, no backwards incompatible changes were found, and all users are encouraged to upgrade when they are ready.

feat: Add support for Django 5

---

globus_portal_framework/__init__.py
globus_portal_framework/gclients.py
globus_portal_framework/gtransfer.py

This function isn't used internally anywhere, and is leftover from older functionality. Its use was discussed, and it's very much something we want to discourage for pretty much all use-cases (It's much better to assume a token is active and deal with it being revoked).
This is an internal function, and more of a refactor, but labeling it a fix so it's noted in changenotes.

fix: Remove un-used validate_token() function

---

docs/requirements.txt

This failed once in automated builds recently, but only for py 3.10. I don't have an explanation for that, or why it didn't fail earlier. But it's an easy fix!

chore: Fix docs build sometimes failing due to bad version string

---

docs/source/reference/migration.rst
docs/source/reference/settings.rst
docs/source/tutorial/portal/custom-urls.rst
docs/source/tutorial/search/custom-views.rst
docs/source/tutorial/search/templates.rst

Specify values in the settings reference, in addition to links to various other helpful docs. Clarify v2 templates are v0.4.x, and v3 templates are v0.5.x.

docs: Clarify v2, v3 template doc settings

---

docs/source/conf.py
docs/source/index.rst
docs/source/reference/urls.rst
docs/source/reference/views.rst
docs/source/tutorial/search/configuring-fields.rst
globus_portal_framework/gclients.py
globus_portal_framework/views/base.py

These don't include functional code changes, but do add some typings to function signatures within code.

Document URLs, Views, and API functions in DGPF

---

.readthedocs.yml

RTD requires a `.readthedocs.yml` file shown below. I was a bit surprised we didn't have this.

Fix Read-The-Docs documentation builds

---

globus_portal_framework/exc.py
globus_portal_framework/gclients.py
globus_portal_framework/settings.py

These changes allow for non-Globus users to load public search clients to view public search data by default, with settings to allow for raising exceptions to handle special cases for non-globus users when they should be redirected somewhere else. This is handy if there are multiple indexes available, and it's desired for a private one to redirect to a Globus Login if desired (via middleware).

feat: Allow non-Globus users to access public search data

---

globus_portal_framework/views/base.py

While making a first PR, I noticed 5 sphinx doc build warnings. I've resolved 4/5, so that any new PR will always show a clean build. 
Two (note/warning boxes) are small but user-facing. Other changes are internal only.
See commit messages for details.
The last remaining warning references a section/method that doesn't seem to exist, and may not have since it was written. @NickolausDS is author of this line, and it's easiest to just ask him original intent. 
`globus_portal_framework/views/base.py:docstring of globus_portal_framework.views.base.search:48: WARNING: undefined label: 'gsearch_reference' [ref.ref]`
I can't find items named `get_search_facets` or `gsearch_reference`, nor any changelog items in relevant timespan.

Fix sphinx doc build warnings

---

docs/requirements.txt
docs/source/examples/built_in_fields.py
docs/source/tutorial/search/configuring-fields.rst
globus_portal_framework/gsearch.py
globus_portal_framework/views/base.py
tests/test_gsearch.py

🦑 Happy to break this up into >1 PRs. It represents a set of tweaks I made to support a particular demo use case.
* Fix an issue where search result links could sometimes generate "subject not found" links for detail pages (due to mixing of not-inverse quote_plus / unquote operations)
*   This manifested when a search index subject id name contained _spaces_
* Improve handling of `fields` in DGPF
*  Explicitly document all three syntaxes that were supported previously, and the need to specify the special template fields explicitly in fields config
* Fix mismatch between doc and project dependencies that prevented local doc build on Py3.13 (cgi module was removed, and old django versions used by docs tried to import it)
* Add missing unit test for existing *(field name, alias)* mode
* …

Fix result retrieval issues

---

docs/source/index.rst
docs/source/reference/index-configuration.rst
globus_portal_framework/checks.py
globus_portal_framework/constants.py
globus_portal_framework/gsearch.py
tests/test_checks.py

Add support for the new query format query#1.0.0. 
See more info for that on [Globus Discuss](https://groups.google.com/a/globus.org/g/discuss/c/IaRLEWbXVr0/m/ZCE5mkqhCgAJ), [Version History](https://docs.globus.org/api/search/changelog/#1_26_0_2024_09_27), and [Query Documentation](https://docs.globus.org/api/search/reference/post_query/#gsearchrequest).
Django Globus Portal Framework itself will allow specifying this version in the SEARCH_INDEXES fields, such as below: 
```
SEARCH_INDEXES = {
'my_index': {
'uuid': 'my_index_uuid',
'@version': 'query#1.0.0',
}
}
```
The `@version` field is optional and will default to the version that Globus Search uses. See the above documentation for when Globus Search will switch to the new version by default.
Please note, that the newer search …

feat: Support new Globus Search query formats (query#1.0.0)

---

docs/source/reference/index-configuration.rst

The current docs page is broken here:
https://django-globus-portal-framework.readthedocs.io/en/latest/reference/index-configuration.html
This was missed in the last PR.

docs: fix code block on index configuration docs page

---

tests/mocks.py

Python Social Auth released an update requiring entries to have unique ids. Tests in DGPF also need to include these ids to pass properly.

chore: Fix tests for python social auth v5.5.1

---

.github/workflows/tests-sdk-v4.yml
globus_portal_framework/auth.py

Scopes changed slightly in the latest version, and comparing them directly to scope strings no longer works. Fix this in auth.py.

fix: Compatibility for Globus SDK v4

---

globus_portal_framework/gsearch.py

Previously, get_template() improperly caught all exceptions. This
would cause templates to automatically fall back to older templates
silently, causing unexpected behavior when defining custom templates
for views.
Fix for https://app.shortcut.com/globus/story/39716/get-templates-improperly-catches-broad-exceptions

fix: get_template will no longer catch broad exceptions

---

docs/source/index.rst
docs/source/reference/templatetags.rst
globus_portal_framework/templatetags/index_template.py
globus_portal_framework/templatetags/is_active.py

These previously weren't documented, but merely existed within the DGPF templates. Docs have been updated so they show up nicely in the RTD

docs: Document template tags
